#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id$
#
# usage: mkmf_perturb_chem_emiss_CORR_RT_MA [ -mpi | -nompi ]
#
# without any args (or with -nompi), builds without mpi libraries, and it will run
# as a serial executable. if -mpi is given, it will be compiled with the mpi
# libraries and can run with multiple cooperating processes.

if ( $#argv > 0 ) then
  if ("$argv[1]" == "-mpi") then
    setenv usingmpi 1
  else if ("$argv[1]" == "-nompi") then
    setenv usingmpi 0
  else
    echo "Unrecognized argument to mkmf_perturb_chem_emiss_CORR_RT_MA: $argv[1]"
    echo "Usage: mkmf_perturb_chem_emiss_CORR_RT_MA [ -mpi | -nompi ]"
    echo " default is to generate a Makefile without MPI support."
    exit -1
  endif
else
  setenv usingmpi 0
endif

# make a backup copy of the path_names file, and then use
# sed to make sure it includes either the non-mpi subroutines,
# or the subroutines which really call mpi.

set pathFile = path_names_perturb_chem_emiss_CORR_RT_MA

cp -f ${pathFile} ${pathFile}.back

if ( $usingmpi ) then

  echo "Makefile uses MPI version of code."
  sed -e 's;/perturb_chem_emiss_CORR_RT_MA;/perturb_chem_emiss_CORR_RT_MA_MPI;' ${pathFile}.back >! ${pathFile}
  setenv wrapper_arg -w
  set EXENAME = perturb_chem_emiss_CORR_RT_MA_MPI.exe

else

  echo "Makefile uses serial version of code."
  sed -e 's;/perturb_chem_emiss_CORR_RT_MA_MPI;/perturb_chem_emiss_CORR_RT_MA;' ${pathFile}.back >! ${pathFile}
  setenv wrapper_arg ""
  set EXENAME = perturb_chem_emiss_CORR_RT_MA.exe

endif

# remove temp file and now really call mkmf to generate makefile
rm -f ${pathFile}.back

    ../../../../../../mkmf/mkmf -p ${EXENAME} \
-t  ../../../../../../mkmf/mkmf.template \
-a "../../../../../.." ${wrapper_arg} ${pathFile}

exit $status

# <next few lines under version control, do not edit>
# $URL$
# $Revision$
# $Date$

